### ISSUE TITLE
bug: Content at homepage seems like distorted

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1004]
_From @rahul-sati on February 28, 2017 6:20_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>It's not related to ionic framework but the site actually.
(https://ionicframework.com/)
At this section "A complete mobile toolkit, built for web developers."
The "Ionicons icon pack includes hundreds of the most common app icons. MIT licensed, and ready out of the box. " looks moved to left a bit.

It's not that big issue but I think if it's related to ionic then it must be perfect.

Thanks
Rahul Sati</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10585_

**Comment by perrygovier** [comment]
@rahul-sati Can you share a screenshot?

**Comment by snewell92** [comment]
Not sure if this is what was meant, but on windows 10, chrome, I squeezed it all the way down to the smallest breakpoint and then I noticed that the icons aren't aligned perfectly. I'm not sure I would worry about it if I were you guys.

![ionicchromesmallbreak](https://cloud.githubusercontent.com/assets/25957964/24960844/ab1a9e64-1f5c-11e7-90e7-a27a268e7de1.JPG)

**Comment by perrygovier** [comment]
The homepage is going to get redesigned soon anyways. I'm going to close this for now.
