### ISSUE TITLE
Update Docs for lodash

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1007]
_From @xindexer on March 3, 2017 17:44_

Please update your changelog to properly reflect how to get lodash to work

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#typings

should have this

npm install @types/lodash@ts2.0 --save-dev --save-exact

(need to add the @ts2.0)

_Copied from original issue: driftyco/ionic#10638_

**Comment by perrygovier** [comment]
@jgw96 shouldn't this have stayed on driftyco/ionic?

**Comment by perrygovier** [comment]
I think this is covered by the 3rd party libs section
