### ISSUE TITLE
bug: Password reset corrections

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1010]
_From @mika-lsv on March 6, 2017 8:33_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I use your password reset form, I receive 2 same email with the reset link. And when I go to the link the text ask me to enter my email for verification and my new password, there is no email input in this page.
And when I finish and clic send there is no confirm message.
The function work well but there is few issues.
Thanks for your work</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10660_

**Comment by mika-lsv** [comment]
Hi guys! Do you have news on this bug?

**Comment by marcorubagotti** [comment]
I have the same problems, we can fix this bugs? It's really misleading for the user :(

**Comment by piotrowski** [comment]
Is this concerning the Ionic Auth password reset page? If not, which page are you referring to?

**Comment by marcorubagotti** [comment]
Yes, https://web.ionic.io/password/reset/[ionic_app_id]
in my case https://web.ionic.io/password/reset/8a921d85
