### ISSUE TITLE
docs: media-plugin is not available today in your websit

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#1027]
_From @yt430010 on March 22, 2017 0:1_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>http://ionicframework.com/docs/v2/native/media-plugin
Ooops. The page you're looking for got lost in space.

The address might be mistyped or the page may have moved.
please fix it</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#10867_

**Comment by perrygovier** [comment]
@goodells, can you add a 301?
