### ISSUE TITLE
docs: Search on doc v1 is broken

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1038]
_From @gerhardcit on April 5, 2017 11:28_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Go to documentation V1 site.
https://ionicframework.com/docs/v1/
Try and search. It's broken. 
Look at the javascript console.. a LOT of http stuff is served with warnings. Which is possibly why the search is broken.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#11062_

**Comment by jgw96** [comment]
_From @MA-Maddin on April 5, 2017 13:27_

It is not just v1 affected but also v2, for more than a week now.

When entering something in search, "API" and "Native" sections stay blank and everything I click in "General" results into the 404 page.

Also many 404 errors in console.

```
GET https://ionicframework.com/docs///tmp/build_74b698d4a948496813b816516102f52f/driftyco-ionic-site-b568e75/content/docs/native/dialogs/ 404 ()
```

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
