### ISSUE TITLE
Docs: Broken link to "Picker API docs" on DateTime Input Properties pickerOptions

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1046]
https://ionicframework.com/docs/api/components/datetime/DateTime/#input-properties => "pickerOptions" => "Picker API docs" links to https://ionicframework.com/docs/api/components/picker/Picker which doesn't exist.

**Comment by danielsogl** [comment]
@piotrowski looks like there is no documentation for the pickerOptions at all.

**Comment by janpio** [comment]
(Just checked again: Still broken, so issue is still valid)

**Comment by goodells** [comment]
It looks like this is being caused because the`Picker` component's stuff isn't making it through the documentation generation process - the component does exist in the Ionic source (see https://github.com/ionic-team/ionic/tree/master/src/components/picker).

This may be related to https://github.com/ionic-team/ionic-site/issues/1104, but I'm not sure yet.  Will investigate more.

**Comment by mhartington** [comment]
This is on purpose. The picker originally wasn't really meant to be used directly by a dev. We could probably instead add a section for the available options. Not sure if we want to fully document picker API.
cc @brandyscarney

**Comment by simonbrazell** [comment]
This is still an issue, Picker API link is broken. 
If we shouldn't use the underlying picker API then why have `pickerOptions` available? Or if we can use only some options then they should at least be stated in the docs for quick reference rather than having to read the source.

**Comment by xinbenlv** [comment]
@mhartington I wish to use the picker as a radio as it's more space efficient

**Comment by thesayyn** [comment]
pickerOptions link is still broken.

**Comment by LucaColombi** [comment]
all above github link are broken, and documentation link too 👎

**Comment by pbrain19** [comment]
Will this get fixed before the 2020 elections?

**Comment by brandyscarney** [comment]
Picker has begun documentation in v4 beta:
- https://beta.ionicframework.com/docs/api/picker
- https://beta.ionicframework.com/docs/api/picker-controller

There isn't much added yet, but it has the basic methods / properties listed. 

There is no need for rude comments. We have higher priority issues that we're working on at the moment and as the documentation and Ionic are both open source, please feel free to make a PR to get it updated faster. Thanks!
