### ISSUE TITLE
Output events aren't documented for inputs anymore

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#1074]
Some output events have disappeared from the documentation since the input refactor.

Most noticeably, `ionChange`:

http://ionicframework.com/docs/api/components/toggle/Toggle/
http://ionicframework.com/docs/api/components/select/Select/#output-events

We need to get these added back in. cc @manucorporat

**Comment by bleuscyther** [comment]
@brandyscarney seem like the select ionChange  disappeared again

**Comment by goodells** [comment]
@mhartington Would you be able to look into this?  It does appear that inherited input events such as `ionChange` were removed from the documentation.  For the `DateTime` input, here is the commit specifically where it was removed:

https://github.com/ionic-team/ionic/commit/9a4d81b3292996539b6c65c2a644eddced29f158#diff-1fcca3ac438be2a7240f9908729616a4L425

**Comment by mhartington** [comment]
This was do to a refactor in all the inputs. We refactored them to inherit from a base class, but in doing so, we loss the input/output events. Dgeni doesn't seem to parse the base class so, we'll need to think of something for this.

**Comment by goodells** [comment]
Hm, if we can't grab those inherited events directly it might be possible to add some kind of notice in the events section of these docs that it has inherited some things from the base input.  Not sure of the implementation of either solution.  CC @perrygovier

**Comment by mhartington** [comment]
if we need to, we can add some placeholder APIs that are just there for docs, pretty sure @brandyscarney  did something similar.

**Comment by ryanhalley** [comment]
I was looking for extra detail on validate()

**Comment by HugoHeneault** [comment]
Came here from one stackoverflow thread https://stackoverflow.com/questions/43185996/subscribe-to-done-event-in-datetime-picker-in-ionic2

It would be useful to get this sorted out :)

**Comment by yeomann** [comment]
still not existing in the API docs

**Comment by luisenrike** [comment]
Still missing

**Comment by edwinm** [comment]
Still not there.

**Comment by brandyscarney** [comment]
I am going to close this since it is unlikely it will be added back in v3, but they are documented properly again in v4: https://beta.ionicframework.com/docs/api/select#events
