### ISSUE TITLE
Include unhappy-path directions

### ISSUE THREAD

**Issue by bdeanindy** [ionic-team/ionic-site#1075]
The following message on [this page](https://ionicframework.com/docs/intro/tutorial/) after using `ionic serve` currently read as,
> "You should see the welcome message shown above if everything was installed successfully".

Would be nice to provide some basic debugging, create issue, FAQ, or other unhappy path helpers in this section if the `ionic serve` command fails.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
