### ISSUE TITLE
Current Framework Docs: Listed template is not available

### ISSUE THREAD

**Issue by DroneZzZko** [ionic-team/ionic-site#1092]
Starter template "super" listed in tutorial is not available.

`ionic start projectName super` produces:

> Unable to find starter template for super

**Comment by danielsogl** [comment]
Hey @DroneZzZko, we will add this template soon back again!

**Comment by danielsogl** [comment]
@DroneZzZko can you close this issue? We added the template back to the CLI with the latest release.
