### ISSUE TITLE
Docs: resize / resume duplicate

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1103]
_From @alexbainbridge on May 14, 2017 1:8_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ *] **3.x**

**I'm submitting a ...**  (check one with "x")
[*] bug report
[ ] feature request

>  resize
> The resize event emits when the native platform pulls the application out from the background. This event would emit when a Cordova app comes out from the background, however, it would not fire on a standard web browser.
> 
>  resume
> The resume event emits when the native platform pulls the application out from the background. This event would emit when a Cordova app comes out from the background, however, it would not fire on a standard web browser.

Pretty sure the resize event is not the same as the resume event, and somehow the resume text has copied to the resize text

https://ionicframework.com/docs/api/platform/Platform/

_Copied from original issue: driftyco/ionic#11655_

**Comment by janpio** [comment]
Source for content is here: https://github.com/ionic-team/ionic/blob/master/src/platform/platform.ts

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
