### ISSUE TITLE
Docs: CLI guide's index doesn't list all pages

### ISSUE THREAD

**Issue by graysonkent** [ionic-team/ionic-site#1104]
I noticed that I can manually navigate to http://ionicframework.com/docs/cli/run/ but it doesn't show up on the sidebar to the left under the CLI documentation tab. Is this intended behavior?
![image](https://cloud.githubusercontent.com/assets/11469730/26072607/1e2f8e6e-397a-11e7-80f2-9e7f0c9329dd.png)

**Comment by piotrowski** [comment]
The `run` command is now `cordova run`: http://ionicframework.com/docs/cli/cordova/run/

I think http://ionicframework.com/docs/cli/run/ is leftover from the old Ionic CLI v2 docs and should be removed.

**Comment by dwieeb** [comment]
@perrygovier These old pages seem to be left over. Can they redirect to their respective `cordova/` page?

**Comment by perrygovier** [comment]
@sam, see me before starting on this one
