### ISSUE TITLE
Docs: Update CLI commands to CLI v3

### ISSUE THREAD

**Issue by piotrowski** [ionic-team/ionic-site#1105]
This issue collects all pages of the docs that still contain Ionic CLI v2 syntax as preparation for a Pull Request:

**`ionic build`**

https://github.com/driftyco/ionic-site/blob/master/content/docs/intro/deploying/index.md

v1:
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/getting-started/index.html
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/installation.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/testing.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/publishing.md

**`ionic emulate`**

https://github.com/driftyco/ionic-site/blob/master/content/docs/resources/developer-tips/index.md

v1:
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/installation.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/getting-started/index.html
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/testing.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/ionic-cli-faq/index.html

**`ionic run`**

https://github.com/driftyco/ionic-site/blob/master/content/docs/intro/deploying/index.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/resources/app-scripts/index.md

v1:
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/concepts/development.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/testing.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/installation.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/ionic-cli-faq/index.html

**`ionic platform`**

https://github.com/driftyco/ionic-site/blob/master/content/docs/cli/platform/index.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/native/geofence/index.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/resources/platform-setup/windows-setup.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/cli/platform/index.md

v1:
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/concepts/development.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/guide/installation.md
https://github.com/driftyco/ionic-site/blob/master/content/docs/v1/getting-started/index.html

**`ionic plugin`**

Not searchable until Native Docs are updated.

**Comment by danielsogl** [comment]
@piotrowski I will fix that
