### ISSUE TITLE
Add note about not using the cordova browser platform

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1106]
We should add a note to recommend users not use the cordova browser platform.

**Comment by piotrowski** [comment]
Please also provide guidance on what to use instead (and how exactly, think of `--prod` etc).

**Comment by mhartington** [comment]
Of course 😄

**Comment by olegwn** [comment]
So what's the recommended way to build for browsers without using 'ionic platform build browser'?

**Comment by janpio** [comment]
`ionic serve` and then copy the content of `www` afaik.

**Comment by olegwn** [comment]
@janpio not the best solution. I need to use `--prod` flag for AoT/production mode and have the correct config variables in [Platform](http://ionicframework.com/docs/api/platform/Platform/) module

**Comment by janpio** [comment]
Then run `npm run ionic:build --prod`.

**Comment by Sneko** [comment]
@jgw96 Hi!

Do you agree that we are required to use browser platform if the app need some cordova plugins (like camera) ?

Thanks

**Comment by soumak77** [comment]
@jgw96 [cordova-browser v5](https://cordova.apache.org/news/2017/08/29/browser-serve-release.html) has been released.  Any idea when Ionic will officially support the browser platform?

**Comment by mhartington** [comment]
We probably wont support/suggest using cordova-browser. It doesn't make sense to use it when only a handful of plugin have support for the platform, and there is progress being made to port core plugins to use up-to-date standard APIs.

**Comment by soumak77** [comment]
@mhartington what is the official Ionic process for deploying a web app if you aren't using the browser platform?

**Comment by janpio** [comment]
@soumak77 `ionic build`

**Comment by amreladawy** [comment]
@soumak77  
`ionic build --prod` then use the `www` folder
