### ISSUE TITLE
Menu Docs with 404 links

### ISSUE THREAD

**Issue by AleFons** [ionic-team/ionic-site#1129]
Some links in the API docs for Menu and related pages are using what seems to be an old link style; here are the ones I've found:

- On https://ionicframework.com/docs/api/components/menu/Menu/ ,
two links to MenuController are linking to https://ionicframework.com/docs/v1/api/components/menu/app/MenuController , instead of https://ionicframework.com/docs/api/components/app/MenuController/

- On https://ionicframework.com/docs/api/components/app/MenuController/ ,
all links to Menu are linking to https://ionicframework.com/docs/v1/api/components/app/Menu , instead of https://ionicframework.com/docs/api/components/menu/Menu/

**Comment by danielsogl** [comment]
@AleFons I will fix that
