### ISSUE TITLE
ionChange event documentation missing on ion-select

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1155]
_From @gaurav-chandra on June 13, 2017 12:8_

https://ionicframework.com/docs/api/components/select/Select/

Output section is missing the documentation of ionChange event.

_Copied from original issue: ionic-team/ionic#12030_

**Comment by mhartington** [comment]
Duplicate of https://github.com/ionic-team/ionic-site/issues/1145.

Classes that extend a base are not generating the docs
