### ISSUE TITLE
Please clarify scenarios/life cycle when Pages are added/removed from cache

### ISSUE THREAD

**Issue by saschwarz** [ionic-team/ionic-site#1165]
Please see the discussion in: https://github.com/ionic-team/ionic/issues/12111

It would be helpful in the lifecycle discussion to include how `setRootPage` and `push`/`pop` affect the page cache and consequently, the lifecycle methods called on the parent and child pages.

**Comment by tnguyen-lh** [comment]
I have the same problem too, in ionic 1 users search for product, page display search results, then he navigate away from the search page, when he click in tool bar to come back search page, ionic 1 provide view-cache=true.
However, when we migrate to ionic 2, that is no longer working, everytime user click back to search results, the state disappears.
I have request a feature from the ionic team, does not seem to move anywhere. [https://github.com/ionic-team/ionic/issues/13838#issuecomment-358617087]
[https://forum.ionicframework.com/t/enable-view-cache-for-ionic/118235]
I don't know ionic team try to ignore this solid case, I'm thinking of moving to React Native when It is availabe in npm 5.
