### ISSUE TITLE
Attributes missing from most API component documentation pages

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1167]
_From @nikmartin on June 23, 2017 16:50_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Pages like: http://ionicframework.com/docs/api/components/toolbar/Header/ have no documentation about the attributes/directives that can be added to components to control their behaviour. For instance, the linked page has no documentation for the no-border attribute. The ion-content page has no documentation for the padding attribute.

**Expected behavior:**
All attributes of each component should  be documented
**Steps to reproduce:**
Navigate to http://ionicframework.com/docs/api/components/toolbar/Header/ and attempt to read about the no-border atribute

_Copied from original issue: ionic-team/ionic#12145_

**Comment by brandyscarney** [comment]
The `padding` attribute can actually be applied to any element, not just content, and has some more information here: http://ionicframework.com/docs/theming/css-utilities/#content-space

There is also some documentation on the `no-border` attribute here: http://ionicframework.com/docs/api/components/toolbar/Toolbar/#header-footer-box-shadow-and-border

Maybe we could move this paragraph to the header/footer documentation?

**Comment by perrygovier** [comment]
cleaning out old docs issues
