### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Nostrus** [ionic-team/ionic-site#1168]
Not sure what happened, but I can't access ionicframework.com since yesterday. 
Same goes for https://ionicthemes.com/, https://market.ionic.io/themes, and strangely enough http://joshmorony.com/, too :) 
I have no problem accessing any other sites, and I haven't had this problem before.
Feel free to close this issue, if everything is fine on your side.

**Comment by janpio** [comment]
None of those are directly related to the repo `ionic-site`. You might want to post at https://forum.ionicframework.com/ though.

**Comment by Nostrus** [comment]
In that case, sorry :) Now they all seem to be working fine again.
