### ISSUE TITLE
Link goes to 404

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1170]
_From @xyluz on June 27, 2017 0:48_

On: https://ionicframework.com/docs/intro/tutorial/
the typescript link goes to a 404.

(image attached
![selection_072](https://user-images.githubusercontent.com/13081285/27566093-9fe6e778-5ada-11e7-8af3-fb4a02bce173.png)
)

_Copied from original issue: ionic-team/ionic#12161_

**Comment by goodells** [comment]
This was resolved in 63f5a7eb6facddae7cb49a7da98f47ff917c5923.
