### ISSUE TITLE
`<ion-buttons start>` not working inside `<ion-navbar>`

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1174]
_From @iget-master on June 30, 2017 17:43_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to just copy and paste documentation example of how to add buttons to a navbar (From here: https://ionicframework.com/docs/components/#buttons-in-components).

The example contains two `ion-buttons` component, with `start` and `end` directives each.
The `end` directive runs fine. The `start` doesn't.

**Expected behavior:**

It should work just as documented, no questions here.

**Steps to reproduce:**

I've made a plunker to reproduce it: http://embed.plnkr.co/KQluWF/

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4 

```

_Copied from original issue: ionic-team/ionic#12223_

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! First of all, sorry about that, but that code snippet is not accurate to that demo. Because of this I am going to move this to the site repo. I made a plunker here https://plnkr.co/edit/KVGciD9u1U3qTvEQ0LNX?p=preview that shows that this is actually working as expected once you add an `ion-title` (which should be in that snippet in the docs). Sorry about that! We will get it fixed up.

**Comment by brandyscarney** [comment]
This is not a documentation issue, please see my comment here https://github.com/ionic-team/ionic/issues/12223#issuecomment-314500797
