### ISSUE TITLE
Add "Demo source" for component API docs

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1179]
Right now the user has to know that the device running running in the component API docs is displaying an app from https://github.com/ionic-team/ionic/tree/master/demos and then look through there to find the actual source code used to produce what he is seeing.

Via the e.g. `* @demo /docs/demos/src/refresher/` the docs of course already knows what to display and could also link to the source (https://github.com/ionic-team/ionic/tree/master/demos/src/refresher) similar to "Demo source" that the component docs have.

**Comment by perrygovier** [comment]
@goodells, let's make a small link to the source in ionic framework
