### ISSUE TITLE
Why gesture api page is not found?

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1185]
_From @moh3n9595 on July 9, 2017 8:23_

hi, I want check gestures and know about swipe more, but this page is not there! why?
[Previous link](https://ionicframework.com/docs/v2/api/components/gestures/Gesture/) :
`https://ionicframework.com/docs/v2/api/components/gestures/Gesture/`

_Copied from original issue: ionic-team/ionic#12295_

**Comment by jgw96** [comment]
_From @AmitMY on July 9, 2017 10:4_

Thanks for opening an issue.
Can you please fill out the template for new issues?
What is the link that got you there?

**Comment by jgw96** [comment]
_From @moh3n9595 on July 9, 2017 10:14_

@AmitMY , It's about gestures and events like `tap,swipe,longpress` and so on

**Comment by jgw96** [comment]
_From @Sampath-Lokuge on July 9, 2017 15:47_

See here: https://ionicframework.com/docs/components/#gestures

**Comment by jgw96** [comment]
_From @wbhob on July 10, 2017 12:43_

Close this?

**Comment by jgw96** [comment]
_From @AmitMY on July 10, 2017 12:48_

@wbhob Still don't know how they got to that link, probably a broken link somewhere, gotta find and fix.

**Comment by mhartington** [comment]
The Gesture page was generated at an earlier time in the framework and currently isn't publicly available to be used.
