### ISSUE TITLE
bug: navigating directly to the docs shows incorrect color links 

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#1186]
Navigating directly to the docs via http://ionicframework.com/docs/ will show the links in the sidemenu as purple and then they change to the correct color.

See the following gif: http://g.recordit.co/iAMyBVRURD.gif

**Comment by goodells** [comment]
This seems to be the result of a CSS transition from the default link color (`rgb(0, 0, 238)`, the purple) to the intended gray.  It's quite unusual for a CSS transition to be invoked upon the page load without any JavaScript, so I'm not really sure how to address the issue directly.  One workaround is to use the `.ng-scope` selector on the body to disable transitions on the affected links until the page has been initialized (thanks @perrygovier).

**Comment by goodells** [comment]
This was resolved in 735174ecf25171cb8ffc2fbcc1a8cc3ede48eb4f.
