### ISSUE TITLE
find a better caching solution for image optimization

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#1192]
On the first run, and occasionally thereafter, `gulp watch` takes a long time to start while it re-processes all the image assets. Can we find a better solution for that? Something where images are still optimized the same, but the only new or updated images are ever processed, even in a fresh clone.

**Comment by goodells** [comment]
The only suggestion I have here is running `npm update` and `npm update --save` to update the versions of the cache- and imagemin-related dependencies in the hope that the issue was resolved by them.  Otherwise, I'm going to wait to experience this first-hand.
