### ISSUE TITLE
More linkable anchors for headlines

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1195]
Pages like https://ionicframework.com/docs/api/components/select/Select/ could really use clickable anchor indicators for the sub-headlines like "Multiple Value: Checkboxes". The anchor is already there, https://ionicframework.com/docs/api/components/select/Select/#multiple-value-checkboxes, but there is no visual indication and you can also not click a nice icon like you can for https://ionicframework.com/docs/api/components/select/Select/#select

**Comment by brandyscarney** [comment]
Possible duplicate of https://github.com/ionic-team/ionic-site/issues/689?

**Comment by brandyscarney** [comment]
@goodells Could we revisit adding #689? Possibly related to https://github.com/ionic-team/ionic-site/issues/557

**Comment by goodells** [comment]
Sure, and I think #557 is the same thing.  I'll see what I can do.
