### ISSUE TITLE
`components-header` and demo "lag" behind real scroll behaviour

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1199]
When you scroll though https://ionicframework.com/docs/components/ the `components-header` and demo often don't really show what I expect it to show . Seems it only changes when the headline of the paragraph I am looking at is fully gone (behind the header) that it switches over. 

I especially noticed this when I scrolled up for the "Demo Source" link and both header and demo changed their content away from what I was looking at.

I suggest this would feel more natural and "precise" if it would switch over sooner (x pixels _before_ headline).

**Comment by janpio** [comment]
I noticed this when I scrolled up for the "Demo Source" link and both header and demo changed their content away from what I was looking at.

**Comment by goodells** [comment]
Not sure of the status on when the fixed header on the components page will change in relation to the page content, but we will be doing some work soon to optimize the transition to be less laggy.

**Comment by janpio** [comment]
Great. 

Using "lag" was a mistake here, as I really didn't mean the performance problems of loading the changing demos but really the "inpreciseness" of what is shown when.

**Comment by perrygovier** [comment]
cleaning out old docs issues
