### ISSUE TITLE
Datetime broken link

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-site#1210]
Look for: "Any additional options that the picker interface can accept", the link to the picker options is broken.
This is the link it shows: https://ionicframework.com/docs/api/components/picker/Picker
Here: https://ionicframework.com/docs/api/components/datetime/DateTime/

**Comment by davec21** [comment]
Just wanted to bump this as it is still an issue.

**Comment by perrygovier** [comment]
Closing as this is fixed in the v4 docs
