### ISSUE TITLE
NavPush and NavPop show "misleading" demo

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1212]
Documentation pages for NavPush and NavPop directives show a demo that seems to do what the docs talk about, but doesn't use the actual directives:

https://ionicframework.com/docs/api/components/nav/NavPush/
https://ionicframework.com/docs/api/components/nav/NavPop/

I didn't find an actual demo for these two directives. But better none than a frustrating one.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
