### ISSUE TITLE
v1 documentation page listed as normal documentation in Google

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1214]
Googling for "ionic navbar button" gives you this result:

![image](https://user-images.githubusercontent.com/183673/28682801-839c207e-72fe-11e7-9b1d-5b58fd9431d9.png)

But clicking on it lands you on https://ionicframework.com/docs/v1/api/directive/ionNavButtons/. This is a bit confusing. The Google snippet should show the actual URL.

Seems there is a redirect in place that google doesn't understand as "the location where you are redirected to should be listed in the Google index".

**Comment by perrygovier** [comment]
This should be fixed now
