### ISSUE TITLE
V2 docs missing swipe animation example

### ISSUE THREAD

**Issue by AndrewLouGeek** [ionic-team/ionic-site#1215]
From the Docs:
https://ionicframework.com/docs/components/#buttons-in-components
"For mobile experiences, Cards make it easy to display the same information visually across many different screen sizes. They allow for more control, are flexible, and can even be animated. Cards are usually placed on top of one another, but they can also be used like a "page" and **swiped** between, left and right. "

If this is something that is currently functionality held within the card system, can you please add some examples? Thank you!

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
