### ISSUE TITLE
Clicking anchors is "animated", but missing actual anchor in URL

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1216]
When you click a headline anchor in the content you are now "animated" to the headline instead of it just jumping, but the URL doesn't actually change to be the URL of the anchor your clicked.

https://ionicframework.com/docs/api/components/label/Label
Click on the chain thing next to a headline, URL stays the same instead of changing to e.g. https://ionicframework.com/docs/api/components/label/Label/#attributes

Win10, Chrome 60

**Comment by janpio** [comment]
Problem also exists on non-docs pages like http://ionicframework.com/products/ where clicking one of the icons for e.g. "Live hot code app updates" (for Ionic Deploy) scrolls down, but doesn't update the URL to http://ionicframework.com/products/#updates

**Comment by jcesarmobile** [comment]
I can't reproduce anymore and the site has changed a lot since 2017, so looks like it was fixed
