### ISSUE TITLE
docs(ionicons): logo icons different from rest

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1218]
http://ionicframework.com/docs/ionicons/

If you search for something, you can normally always use the value from the "Name" column as the `name`  of `ion-icon`: `<ion-icon name="star"></ion-icon>`.

This doesn't work for e.g. "twitter" or "twitch" where you have to use `logo-twitter` which is only visible after clicking the icon to get the popup. 

This might be confusing (I know it was to me).

**Comment by beck24** [comment]
This caught me a couple of days ago...

**Comment by ciaran036** [comment]
This definitely needs to be documented. Something as simple as this shouldn't be left for us to scour Ionic forum posts for an answer for.

**Comment by ahtsei** [comment]
I got tripped up on this one today as well.

I had a look at what's involved in updating the docs, setup this repo locally, ran gulp watch but then got stuck. Would it be just a matter of updating the icon 'keys' in this configuration file:

https://github.com/ionic-team/ionic-site/blob/master/content/docs/ionicons/site_data.json

Happy to update it if I could get some guidance?
