### ISSUE TITLE
Search doesn't return result from Components, only API & Native

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic-site#1220]
Why when I search for something (say 'badge') do I get results for both the badge API & Native. No results ever show up from Components.  I can click on the api result and then click the 'related' link to the component Documents, but this is cumbersome.  Why not show component results while searching?

**Comment by MartinMuzatko** [comment]
Agreed. The search is really obtrusive.

**Comment by perrygovier** [comment]
Super delayed response, we've totally overhauled search and I think it's much better now
