### ISSUE TITLE
Documentation sidebar scroll offset is changed when the main content is scrolled to the top

### ISSUE THREAD

**Issue by goodells** [ionic-team/ionic-site#1221]
Not sure if this behavior is intentional, but it is extremely jarring in e.g. the Ionic Native docs.

To reproduce:

1. Go to something like [Ionic Native > Native Audio](http://ionicframework.com/docs/native/native-audio/) with that link visible in the sidebar
2. Scroll down in the documentation content
3. Scroll back up to the top in the documentation content

The sidebar navigation will now be scrolled close to the top as well, and the Native Audio link won't be visible, requiring the user to scroll all the way back down in the sidebar to choose something close to it.

**Comment by goleary** [comment]
seeing the same

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
