### ISSUE TITLE
Scrolling in Component docs is acting wonky

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic-site#1222]
To reproduce:

1. go here: http://ionicframework.com/docs/components/
2. scroll down to prompt alerts (or any other section)
3. scroll back up to just above the prompt alerts section

the whole page  jolts back to a previous (lower) scroll position.

**Comment by goodells** [comment]
Thanks for reporting this and giving concrete steps to reproduce the issue.  I think I've narrowed it down to something with the fixed header on the components page - will look into this and try to get a fix out ASAP.

**Comment by goleary** [comment]
still experiencing this...any status update?

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
