### ISSUE TITLE
Assets of /docs/demos are duplicated for each demo

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1224]
Assets of /docs/demos/src/* are identical in each demo and loaded from a subfolder.

Deduplicating these could improve the loading time of the demos.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
