### ISSUE TITLE
Trailing Slash is missing in links

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1228]
Similar to #1226, #1223 and #1227 the trailing slash is missing in a lot of links and menus, requiring an additional redirect after clicking the link until the page can actually be shown to the user.

These haven't been covered by the previous issues yet:

- https://ionicframework.com/docs/ - All links under "Intro" are missing the trailing slash (problem though missing on all pages that show this navigation - a lot)
- https://ionicframework.com/docs/ - "API"
- Several scattered links in content itself. Doesn't make sense to hunt for them now, will be much easier wenn all the other issues were fixed by merging the PRs.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
