### ISSUE TITLE
Docs - Tutorial "Project Structure" doesn't match "super" template

### ISSUE THREAD

**Issue by ZaLiTHkA** [ionic-team/ionic-site#1234]
Greetings.. I'm trying to work out how to get started with Ionic Framework, but because I have no experience with TS, this is turning out to be quite a challenge. Then I thought to myself, at least Ionic has pretty good documentation, so this shouldn't be too hard.

Anyway, in the tutorial page for [Project Structure](https://ionicframework.com/docs//intro/tutorial/project-structure/), it states:

> In `app.component.ts`, we’re setting our template to `src/app/app.html`, so let’s look in there.

But now the `src/app/app.html` file doesn't exist in my project (generated using the `super` template).. Instead, my `app.components.ts` file contains:

    @Component({
      template: '<markup here>'
    })

Furthermore, the markup my file actually contains doesn't match that seen in the documentation. Thanks to the whole butterfly effect idea, the generated project and documentation continue to go off in different directions from this point on. Does the documentation need to updated to match the template, or the other way around?

**Comment by janpio** [comment]
Actully, probably none of both ;)

The tutorial is using a project generated with this command:

`ionic start MyIonicProject tutorial`

https://ionicframework.com/docs/intro/tutorial/

Try that and see if it matches the docs. (Mismatch is still entirely possible of course)

**Comment by ZaLiTHkA** [comment]
Well now... I feel like a real bright spark. :blush: Thanks @janpio, not sure what I was thinking there..

And my apologies for my rather brash post, I wasn't exactly having a good day and my general irritation kinda slipped through a bit in my original message. I'll run through the docs again with the *proper* tutorial code and see what I can learn from it. :)
