### ISSUE TITLE
Demo images don't work in Safari

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic-site#1246]
None of the demo images in the api docs are shown in Safari ([example](http://ionicframework.com/docs/api/components/toolbar/Toolbar/)).

**Comment by perrygovier** [comment]
it's been a longstanding issue. @kensodemann just fixed it

**Comment by shaneparsons** [comment]
@perrygovier It appears the issue has re-surfaced with the 3.7.1 update.

**Comment by kensodemann** [comment]
@shaneparsons - do you have a specific example? I just tried and they all seem to be working for me, including the sample you linked previously.

**Comment by perrygovier** [comment]
Your example link works fine for me in safari. Can you give me any more specifics? URL, browser version, console errors.

**Comment by shaneparsons** [comment]
Hmm strange... The link in the first post isn't working for me, along with everything else on the api page. Here are some specifics:

Safari: `10.1.1 `
Console: `SyntaxError: Cannot declare a let variable twice: 't'. – main.js:1`

Let me know if you need anything else.

**Comment by perrygovier** [comment]
@shaneparsons I don't have Safari 10 on a laptop anymore, but I think we have a fix. Does this work now? http://ionic-site-staging.herokuapp.com/docs/api/util/Events/

**Comment by shaneparsons** [comment]
Yup, seems to work now!

**Comment by perrygovier** [comment]
Thanks! It will be a part of the next deploy. Likely this afternoon.
