### ISSUE TITLE
Tutorial: link to "command line" doesn't work

### ISSUE THREAD

**Issue by hyseneim** [ionic-team/ionic-site#1247]
In:
https://ionicframework.com/docs/intro/tutorial/
At begin, "**command line**" link go to:
https://ionicframework.com/docs//resources/what-is/#cli
404 page not found
Could it be corrected with the following?
https://ionicframework.com/docs/resources/what-is/#cli
Thanks

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
