### ISSUE TITLE
duplication in the sass variables

### ISSUE THREAD

**Issue by aaalsubaie** [ionic-team/ionic-site#1248]
in this page:
https://ionicframework.com/docs/theming/overriding-ionic-variables/

duplication as in the attached image
<img width="1250" alt="screen shot 2017-09-11 at 8 30 22 am" src="https://user-images.githubusercontent.com/1550029/30259724-9ec37104-96cb-11e7-83cf-d2053b22fd58.png">

**Comment by brandyscarney** [comment]
Thanks for the issue! This is caused by the Sass variables being included in both of the theme files. Closing this is a duplicate of https://github.com/ionic-team/ionic-site/issues/846
