### ISSUE TITLE
Ionic Native pages use default text for link preview

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1253]
Example:
https://ionicframework.com/docs/native/is-debug/

looks like this when posted in the forum:
![image](https://user-images.githubusercontent.com/183673/30444175-512e4f86-9982-11e7-9f0e-87286bbeaa93.png)
Same for Twitter, Facebook etc.

As do all the other pages:
https://ionicframework.com/docs/native/browser.html
https://ionicframework.com/docs/native/action-sheet/
...

 Title and description are the default ones instead of available text from the actual pages.

**Comment by janpio** [comment]
Probably covered by this PR I made some time ago: #1161

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
