### ISSUE TITLE
Hamburger menu in docs doesn't work in Firefox mobile for Android 

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-site#1254]
Ionicframework.com/docs

None of the hamburger menu in the ionicframework.com/docs/api or ionicframework.com/docs works as  it should on Firefox for Android or Windows. A list of links don't appear like it does on desktop.

**Comment by Bandito11** [comment]
Still not working with the latest update up to this date.

**Comment by Bandito11** [comment]
Btw this is not working on either Firefox for Android or Firefox for Windows.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
