### ISSUE TITLE
ionViewWillLoad docs are missing

### ISSUE THREAD

**Issue by aaalsubaie** [ionic-team/ionic-site#1258]
I could not find the ionViewWillLoad event in ionic 2 docs! was it decommissioned? it works in code.

https://ionicframework.com/docs/api/navigation/NavController/

**Comment by rjberry95** [comment]
Is there an update on this? I'm working on an ionic 3 app, and I'd like to know if we need to refactor if this lifecycle event is no longer stable.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
