### ISSUE TITLE
Card background docs are perpetuating a bad developing standard

### ISSUE THREAD

**Issue by MartinMuzatko** [ionic-team/ionic-site#1282]
Hello!

The examples in the documentation for the [cards ](https://ionicframework.com/docs/components/#card-background)are not really helping to build a scale-able and maintainable app.

Shouldn't you use a ion-grid with a centered row/column? (`align-items-center`) Instead of absolute positioned texts with magic numbers (`top: 36%`)

![image](https://user-images.githubusercontent.com/2950505/31534073-8d101776-aff5-11e7-8e88-8dd82e73402c.png)

I know that on mobile you can only have a sensible amount of text in place to avoid this kind of case.
Why are you using the element selector directly within `.card-background-page`?
This makes the user implementing this example really unflexible for future updates. Maybe I am a little too pedant here, since I'm using BEM to architecture my CSS.

Hope to see that someone agrees with my views.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. This is fixed in modern Ionic. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
