### ISSUE TITLE
Add wkwebview dependency reference to relevant doc pages

### ISSUE THREAD

**Issue by attilavago** [ionic-team/ionic-site#1283]
This issue is based on: https://forum.ionicframework.com/t/ionic-pro-view-image-issues-wonky-paths/108726/5

The requirement is to add a callout with a reference link to plugins and elements that require wkwebview to work properly in the new Ionic Pro (and Ionic View Pro) platform. This would help developers prevent needles debugging.

For instance the camera plugin requires this to show the image in the view once it has been taken, yet the docs make no reference to this requirement: http://ionicframework.com/docs/native/camera/

I am happy to contribute with this information to the docs myself if I am given a styleguide as to how it's preferred to be written and styled.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
