### ISSUE TITLE
Docs: Downgrading to UIWebView section is missing important steps

### ISSUE THREAD

**Issue by serpaulius** [ionic-team/ionic-site#1286]
When one downgrades back to UIWebView, the bouncing effect is added on the main Ionic content view, and the problem with status bar padding appears again (see https://github.com/ionic-team/ionic/issues/12958).

To fix those problems, two additional steps need to be done (I think this needs to be added to the Downgrading to UIWebView section - https://ionicframework.com/docs/wkwebview/#downgrading-to-uiwebview):

1. Remove the "viewport-fit=cover" option from the "viewport" meta tag in index.html file.
2. add 3 preferences to config.xml file:

`
<preference name="webviewbounce" value="false" />
`
`
<preference name="UIWebViewBounce" value="false" />
`
`
<preference name="DisallowOverscroll" value="true" />
`

**Comment by sahyun1** [comment]
This solved my problem! 
Had that weird 20px blank padding so converted to WKWebView but had issue with CORS so I had to downgrade back to UIWebView

**Comment by mhartington** [comment]
Mind sending a PR for this? Would love to get this added in

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
