### ISSUE TITLE
Cannot install - cannot get ionicate

### ISSUE THREAD

**Issue by iget-esoares** [ionic-team/ionic-site#1293]
Trying to develop locally over this repository to send some pull requests, but following the installation on readme don't work.

The package.json depends on a private repository (ionic-team/ionicate) that as I said, isn't public.

So the `npm install` fails:

> npm ERR! Command failed: git clone --template=/home/esoares/.npm/_git-remotes/_templates --mirror git@github.com:driftyco/ionicate.git /home/esoares/.npm/_git-remotes/git-github-com-driftyco-ionicate-git-cae5a00-6e1196c5
> npm ERR! Cloning into bare repository '/home/esoares/.npm/_git-remotes/git-github-com-driftyco-ionicate-git-cae5a00-6e1196c5'...
> npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
> npm ERR! ERROR: Repository not found.
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR! 
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>

The repo is available on npm repository as `ionicate`, so why do `package.json` refers to a specific commit on that private git repository?

**Comment by ahtsei** [comment]
Looks like this has been fixed now:
https://github.com/ionic-team/ionic-site/commit/5a71344c3ccbc03c08315f1f02a3bc992fe77cac

**Comment by perrygovier** [comment]
Sorry about that!
