### ISSUE TITLE
Link to blog fails over https

### ISSUE THREAD

**Issue by eduardoRoth** [ionic-team/ionic-site#1297]
The link to the blog in the main page goes to the https site, but the site references content over http so it fails to load some files, and the site doesn't load properly.

```
Mixed Content: The page at 'https://blog.ionicframework.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.ionicframework.com/wp-content/themes/ionic/style.css?2'. This request has been blocked; the content must be served over HTTPS.
```

![image](https://user-images.githubusercontent.com/5419161/33104106-0e6ccbf6-ceec-11e7-92c3-be563dcfa028.png)

**Comment by ahtsei** [comment]
Looks like this has been fixed.
