### ISSUE TITLE
Ionic Native Image Picker documentation

### ISSUE THREAD

**Issue by mikemichaelis** [ionic-team/ionic-site#1311]
https://ionicframework.com/docs/native/image-picker/

This page is very clean yet very confusing.  The first thing it says is 

Requires Cordova plugin: cordova-plugin-image-picker

with a following link to the wymsee implementation of this plugin.

Then there is another link to the Telerik implementation of this plugin.

Which should be used Telerik or wmysee?

The installation instructions then show installing the Telerik plugin.  

So I wonder why the first thing on this page is a statement of a requirement to a plugin that is not actually used.

Thanks

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
