### ISSUE TITLE
Indonesian Translation for IONIC Framework Documentation 

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#1327]
_From @iqbalhood on February 19, 2018 8:2_

Hi, Can I contribute to translate IONIC Framework documentation into Indonesian Language?

_Copied from original issue: ionic-team/ionic#14044_

**Comment by iqbalhood** [comment]
Hi, Can I contribute to translate IONIC Framework documentation into Indonesian Language?
