### ISSUE TITLE
docs(registerModeConfigs): empty page

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#1328]
_From @danielsogl on September 24, 2017 14:11_

**Resources:**
No docs content avaiable: https://ionicframework.com/docs/api/config/registerModeConfigs/

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

_Copied from original issue: ionic-team/ionic#12973_

**Comment by danielsogl** [comment]
Still a problem :/

**Comment by brandyscarney** [comment]
I'm going to close this as this is not something that exists in v4 and we're unlikely to go back and add it for v3. If you feel strongly about this being added to the v3 docs please create a PR, thanks!
