### ISSUE TITLE
no padding css utilities

### ISSUE THREAD

**Issue by yashdabi** [ionic-team/ionic-site#1329]
if there are options of adding padding from every side then there should be options of no-padding padding on every side like e.g no-padding-left,no-padding-right, no-padding-top,no-padding-bottom,no-padding-horizontal, no-padding-vertical

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
