### ISSUE TITLE
ionic site metadata for preview snippets

### ISSUE THREAD

**Issue by bwhiting2356** [ionic-team/ionic-site#1332]
When linking to a page on the ionic documentation, the preview that is generated ends up having generic information about Ionic ("Ionic is the app platform for web developers. Build amazing mobile, web, and desktop apps all with one shared code base and open web standards") rather than specific preview text for that page.

Please make the changes to the metadata so that this will happen.

**Comment by perrygovier** [comment]
Sorry for the very delayed response. This was fixed some time last year.
