### ISSUE TITLE
FAB preview broken on Android and Windows.

### ISSUE THREAD

**Issue by synga** [ionic-team/ionic-site#1368]
When looking at the android preview example for [FABs](https://ionicframework.com/docs/components/#fabs) i noticed that it's broken. The fab with `right top edge` attributes is somehow over the statusbar and not over the header as it should be.

As one can see by the image bellow the height of the iframe is way bigger than the background image of its parent. The same goes to Windows.
![fab](https://user-images.githubusercontent.com/9086829/39628034-1d03fea6-4f7e-11e8-8016-cb83798477ff.png)

Didn't found where to fix it so opened a issue.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
