### ISSUE TITLE
Information on Project Structure in the tutorial doesn't match what's generated in a tutorial app

### ISSUE THREAD

**Issue by rushabhshah011** [ionic-team/ionic-site#1386]
Over on this [page](https://ionicframework.com/docs/intro/tutorial/project-structure/), the following text appears:

> Near the top of the file, we should see this:
`@NgModule({
  declarations: [MyApp, HelloIonicPage, ItemDetailsPage, ListPage],
  imports: [BrowserModule, IonicModule.forRoot(MyApp)],
  bootstrap: [IonicApp],
  entryComponents: [MyApp, HelloIonicPage, ItemDetailsPage, ListPage],
  providers: []
})
export class AppModule {}`

However, when I built a tutorial app, the src/app/app.module.ts page actually contained:

`@NgModule({
  declarations: [
    MyApp,
    HelloIonicPage,
    ItemDetailsPage,
    ListPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HelloIonicPage,
    ItemDetailsPage,
    ListPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})`

Relevant github page is [here](https://github.com/ionic-team/ionic-site/edit/master/content/docs/intro/tutorial/project-structure/index.md).

#1384 PR contains refactored code.

@mhartington , @perrygovier  Please review PR.

**Comment by perrygovier** [comment]
merged a while back
