### ISSUE TITLE
/formulas/localstorage page is redirected

### ISSUE THREAD

**Issue by slang800** [ionic-team/ionic-site#1388]
I followed a link from `https://stackoverflow.com/questions/31139365/can-you-use-cookies-in-a-cordova-application` to `http://learn.ionicframework.com/formulas/localstorage/`. The page loaded correctly, but after a couple seconds I was redirected to `https://ionicframework.com/getting-started`

This bug exists in both Chromium and Firefox.

**Comment by mhartington** [comment]
The learn ionic site was an old project that is no long being actively worked on. The achieved version of the site source, including articles can be found here

https://github.com/ionic-team/ionic-learn

**Comment by slang800** [comment]
I can't open up an issue on that repo because it's archived.

**Comment by mhartington** [comment]
Yes, the site is no longer being worked on and is no long active. But the source and content of the article in question are available to browser.

**Comment by slang800** [comment]
> ...content of the article in question are available to browser

No, the page is broken because of the redirect that I described in my first comment. If I want to read the article I need to either disallow redirects on `learn.ionicframework.com` or go to an archived version at `http://web.archive.org/web/20150318035057/http://learn.ionicframework.com/formulas/localstorage/`
