### ISSUE TITLE
https://ionicframework.com/docs/storage/ - 404

### ISSUE THREAD

**Issue by HarveyDanger** [ionic-team/ionic-site#1406]
Hi, it seems that commit
https://github.com/ionic-team/ionic-site/commit/a010a085e3c5ee54f354e17d757886ab8e9adffd
deleted the storage page from the web resource. 

It is currently inaccessible.

**Comment by mhartington** [comment]
Looking into this.

**Comment by perrygovier** [comment]
fixed in https://github.com/ionic-team/ionic-storage/commit/5fb02b5f44a364b362880a774180c642147998ea
