### ISSUE TITLE
The Docs section for the beta version of the framework don't work on Firefox. I  click a path like installation and it doesn't redirect to the path.

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-site#1409]
https://beta.ionicframework.com/docs/

When using in Firefox I can't go to any of the paths.

Ex.
I go to the link above.
I click the widget called UI Components. (I expect to go the Components section in the docs)
it doesn't go anywhere. The path at the address bar changes to https://beta.ionicframework.com/docs/components but I don't get redirected there.

![ionic site error](https://user-images.githubusercontent.com/9807561/46270013-e95bf080-c512-11e8-865d-972eee5cc536.png)

This is what is presented in my Console.

**Comment by perrygovier** [comment]
This is fixed now
