### ISSUE TITLE
Nav control docs can be improved

### ISSUE THREAD

**Issue by glennlawyer** [ionic-team/ionic-site#1436]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
IMPROVE THIS DOC suggestion

comment one: your doc pages include an "improve this doc" link which brings me here, yet the "I'm submitting a ..." does not list "improve this doc" as an option.

The real issue: The docs for NavController, 
https://ionicframework.com/docs/api/navigation/NavController/
have an example which includes this code:
```
pushPage() {
      this.viewCtrl.dismiss();
      this.appCtrl.getRootNav().push(SecondPage);
    }
```
However,  the code `getRootNav` is marked as depreciated.

The docs should be updated to show the proper way to call the function.

[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
