### ISSUE TITLE
new docs are missing the API section that V3 docs had

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-site#1454]
Hi

I was trying too look for info about **Platform** when I noticed I couldn't see the JavaScript API section in the new V4 docs. I been using the V3 docs for any extra info I may need.

I don't know what's implemented or not but a lot of information concerning the JavaScript API is still missing.

Regards,
Esteban

**Comment by perrygovier** [comment]
Hey @Bandito11, we deliberately merged the components page and the API pages here:
https://ionicframework.com/docs/components

Some non-component sections are missing though. There's a relate issue on the docs repo here:
https://github.com/ionic-team/ionic-docs/issues/253

We'll be tackling docs issues a lot over the next few weeks and I think this is one of the top items on the list.

**Comment by Bandito11** [comment]
Yeah I notice that but there were some missing API there like Platform for example. Which funnily enough was recommended to use for platform specific code in the docs.

Thanks!
Esteban Morales

________________________________
