### ISSUE TITLE
ActionSheetController code is not the same one as example [v3]

### ISSUE THREAD

**Issue by NetoLozano** [ionic-team/ionic-site#1459]
The One from the code:
![image](https://user-images.githubusercontent.com/20343160/52543472-9111e680-2d6f-11e9-92a5-9809aaf51f71.png)

What it supposed to look like:

![image](https://user-images.githubusercontent.com/20343160/52543483-ad158800-2d6f-11e9-9e76-864601ab3fc0.png)

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
