### ISSUE TITLE
Typo in Core Values

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-site#1487]
There is a typo for the word "process" on your values page. 

https://github.com/ionic-team/ionic-site/blob/5fac84e89a9a1e7b009cd6d7581c93dcf52a6dba/server/pages/values.html#L36

**Comment by wpnzach** [comment]
I don't think this is a typo...prowess is a real work and works in context

**Comment by sean-perkins** [comment]
@wpnzach you are absolutely correct! I guess you learn something new every day. Sounds like I need to pick-up a few more books 👍
