### ISSUE TITLE
Missing publishing dates on blog articles

### ISSUE THREAD

**Issue by dessant** [ionic-team/ionic-site#1488]
The [blog](https://ionicframework.com/blog/) posts do not have a visible publishing date. It would be of great help for those who are just discovering Ionic and Capacitor and would like to quickly get a sense of the timeline of announcements when they browse the blog, and it's generally a good thing to have those dates visible.

Ionic and Capacitor are a joy to use, thanks for all your awesome work!

**Comment by perrygovier** [comment]
Good point, thanks. I'll try to find time to fix it soon.

**Comment by perrygovier** [comment]
I should have checked before I commented. There's a date beneath the title. Are you able to share more info or a link to a post that doesn't have a date? 

![Screen Shot 2019-10-11 at 10 24 02 AM](https://user-images.githubusercontent.com/571056/66664108-8c107a00-ec11-11e9-902e-73716f1f1218.png)

**Comment by dessant** [comment]
I have disabled uBlock Origin and indeed the widget with the author and date is there. The entire widget is hidden when `Fanboy's Annoyance List` or `Fanboy’s Social Blocking List` is enabled, because of the `post-social` CSS class.

That class name is associated with social sharing, so it could be blocked by other filter lists too. In any case, sorry for the bug report, I should have checked my ad blocker first.
