### ISSUE TITLE
typo on new x landing page - "progressiveweb apps"

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-site#1497]
Can't find this to do my own PR but there is a typo in the new X landing page:

Missing space between "progressiveweb"

![image](https://user-images.githubusercontent.com/1038062/73344407-39b79f80-427a-11ea-9b3e-ea02fa54af9d.png)

https://ionicframework.com/x

**Comment by perrygovier** [comment]
Thanks! Fixed in Prismic. Should be live as Cloudflare cache cycles.
