### ISSUE TITLE
duplicate text on new x landing page "app integrations"

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-site#1498]
Not sure what it was supposed to say but there are two "app integrations" (top right and bottom left in screenshot):

![image](https://user-images.githubusercontent.com/1038062/73344520-6b306b00-427a-11ea-8997-97f1d70fc8d7.png)

https://ionicframework.com/x

**Comment by perrygovier** [comment]
Thanks! Fixed in Prismic. Should be live as Cloudflare cache cycles.
