### ISSUE TITLE
blog post wording - your first ionic app tutorials

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-site#1499]
The [new blog post](https://ionicframework.com/blog/new-photo-gallery-tutorial-for-angular-react-and-capacitor/) starts off funny:

> __A__ new “Your First Ionic App” tutorial for Angular and React __are__ now available! Learn the fundamentals of Ionic app development by creating a real app step by step.

I think it should be:

> __New__ “Your First Ionic App” tutorial**s** for Angular and React are now available! Learn the fundamentals of Ionic app development by creating a real app step by step.

Also, not sure Photo Gallery should have the caps?

**Comment by dotNetkow** [comment]
thanks - updated. Although "Photo Gallery" I'm keeping for artistic purposes :)
