### ISSUE TITLE
Typo in Footer

### ISSUE THREAD

**Issue by shimonosatoru** [ionic-team/ionic-site#1502]
I found typo link in footer "https://ionicframeowork.com/docs" but I cannot access this link.
"https://ionicframework.com/docs" is correct
https://github.com/ionic-team/ionic-site/blob/596c5a058931d0f50c7cfa8e2a98cd3b5780c934/server/pages/_includes/footer.html#L32

**Comment by perrygovier** [comment]
Thanks!
