### ISSUE TITLE
Bug: Community-Section image is not showing

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-site#1543]
The image at the community section is not visible.

![image](https://user-images.githubusercontent.com/36629890/85198890-16a29080-b2ec-11ea-9fbd-e234f4c0d498.png)

**Comment by perrygovier** [comment]
!! I saw that but thought it was just because I'm on a slow internet connection. Thank you very much. fixed in https://github.com/ionic-team/ionic-site/commit/07a807816eafdd053529c58c16665cec55c94597
