### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by TheEvilSkeleton** [ionic-team/ionic-site#1553]
Related to https://github.com/ionic-team/ionic-site/pull/1546,

There is a great alternative to Google Analytics called [Matomo](https://matomo.org/). There is a comparison between Matomo and Google Analytics: https://matomo.org/matomo-vs-google-analytics-comparison/

**Comment by perrygovier** [comment]
Yes, I'm aware of Matomo. In the last 30 days, we had 5.9m page views. Despite our traffic, we're still a small company and require solutions that do not need much of our time to set up and manage. More importantly, at our traffic levels, the price for Matomo would be $1.6k/mo. There's no way I'm getting that approved when GA is free. 

We see this a lot as an OSS company. On one hand, we have the massive traffic levels of the open-source community, on the other, we're still a company trying to make money, so we don't qualify under many "free for open source" programs. If we had the time and money, I'd love to give a shot, but unfortunately, we don't.
