### ISSUE TITLE
feat: publicize real world performance comparisons versus competitors

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-site#1571]
For example you should join the imitation game scientific experiment. 
https://github.com/flutter/flutter/issues/47561

Designing demo apps showing real world tasks, and the benchmarcks results for flutter, Ionic and native would show to the world the representative relative performance of an UI framework vs another.
Ionic suffer from the outdated myth that chromium is slow. You need to show to the world, with "scientific" evidence and fair, open source comparisons that Ionic is competitive in performance (I actually suspect it to be the fatest). Depending on the results, it could skyrocket Ionic adoption!
(bonus, bench with Angular, React and Vue, React would be the most pragmatic as it would allow an almost one to one comparison with react native performance)

You could use metrics such as scrolling performance, first time to paint, power efficiency, https://www.vsynctester.com ,etc)

Such a benchmarck suite, if automated, could allow to track and catch performance regressions over time too!

I really believe this is the next Big thing in Ionic adoption

sidenote I hope you're using optimizing css properties such as will-change, css contain, etc cf: https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS
https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML
(using well and to it's full extant css: contain is a game changer)

**Comment by LifeIsStrange** [comment]
> The "scientific" evidence is - Native applications will always be faster
This is an extremely dumb statement that shows a total absence of knowledge regarding the rendering engines used.
In addition to the various advanced optimizations that chromium has that flutter do not, the support for CSS contain (style, layout, paint, size) enable order of magnitude superior performance in various cases.

**Comment by jcesarmobile** [comment]
Ionic vs React Native
https://ionic.io/blog/ionic-vs-react-native-performance-comparison
