### ISSUE TITLE
Resources page uses a buggy version of `<site-header>`

### ISSUE THREAD

**Issue by robertandrewblackburn** [ionic-team/ionic-site#1574]
Just jumped on to the site to have a look and found the [Resources](https://ionicframework.com/resources) page had an old/buggy <site-header>.
The megamenu dropdowns are unusable as they close as soon as you move your cursor off the heading.

Attached a screen-recording (zipped .mkv) showing the issue.

[2020-11-22 10-27-27.mkv.zip](https://github.com/ionic-team/ionic-site/files/5578681/2020-11-22.10-27-27.mkv.zip)

**Comment by jcesarmobile** [comment]
This is no longer happening
