### ISSUE TITLE
Articles page points to wrong URL when "See all customers" is clicked.

### ISSUE THREAD

**Issue by Rofrtd** [ionic-team/ionic-site#1583]
When reading any article from the Resources page, if you click the "See All Customers" link at the bottom of the article, you are taken to a wrong URL (https://ionicframework.com/resources/customers) which gives a 404. 

The expected behaviour would be to point to https://ionicframework.com/customers.

How to test:
1 - Open the Resources page - https://ionicframework.com/resources
2 - Open any of the resources - https://ionicframework.com/resources/articles/ionic-react-vs-react-native for example
3 - Scroll down the page and click on SEE ALL CUSTOMERS
![Screen Shot 2021-02-22 at 8 06 45 pm](https://user-images.githubusercontent.com/25412194/108686528-a9659000-7549-11eb-8899-de457dce45e8.png)

**Comment by perrygovier** [comment]
Fixed, thanks!
