### ISSUE TITLE
bug: Component docs: "Copy" code block button appears above toolbar

### ISSUE THREAD

**Issue by zrev2220** [ionic-team/ionic-site#1608]
See the screen recording below (captured on [this page](https://ionicframework.com/docs/api/popover), though the issue appears across other components' pages).

Likely, this is just a `z-index` issue with the "Copy" buttons.

https://user-images.githubusercontent.com/22283396/138758366-c42004a6-9f74-4a5d-b732-2dc96a94be2a.mp4

**Comment by jcesarmobile** [comment]
Looks like it was fixed
