### ISSUE TITLE
Build your first app Angular uses deprecated cameraPhoto object

### ISSUE THREAD

**Issue by ne6toto** [ionic-team/ionic-site#1609]
Hi, I am new here, but I believe I found the following issue while working through the "Build your first app" excercise with Angular:

The "Saving Photos to the Filesystem" instructs the user to use the CameraPhoto object in 
`private async savePicture(cameraPhoto: CameraPhoto) { }`
Looking through `@capacitor`'s Camera definitions.d.ts file it seems that CameraPhoto is deprecated, and that Photo should be used instead. This would however result in a name conflict with the previous step, where the user declares an interface with the same name:
`export interface Photo {
  filepath: string;
  webviewPath: string;
}`

I would be happy to submit a pull request for this, but I was unable to find the code responsible for that webpage in this repository.

**Comment by jcesarmobile** [comment]
Thanks for the issue, it was fixed long ago.
The proper repository for issues on the docs is https://github.com/ionic-team/ionic-docs/issues
