### ISSUE TITLE
On Startpage Github Icon refers to wrong Link. 

### ISSUE THREAD

**Issue by Newspicel** [ionic-team/ionic-site#1625]
In the element: site-header__link icon the link does not redirect to github.com but to https://ionicframework.com/github.com/ionic-team which redirects to a 404. 

![Screenshot](https://user-images.githubusercontent.com/32611293/189183818-609d5e51-6cee-4790-a2c4-711b1095fff7.png)

**Comment by jcesarmobile** [comment]
I can't reproduce, so it was probably fixed
