### ISSUE TITLE
Maybe a mistake in github stars

### ISSUE THREAD

**Issue by Ucok23** [ionic-team/ionic-site#1629]
![Screenshot from 2023-04-03 17-55-05](https://user-images.githubusercontent.com/42701951/229490370-0ffb01c6-20fb-4da8-b81c-e4e44b779fb6.png)
 
In Github stars section, first it mention 47k, and it mention again that the github stars is 122k

Maybe a litle mistake, but I confuse and got to the repo, it 47k, so what's 122k?

**Comment by felipebhz** [comment]
I noticed that same thing today. Seems they need to change the 122k from GitHub Stars to Twitter followers. On Twitter they have 123K followers.

![image](https://github.com/ionic-team/ionic-site/assets/1553350/7099c9c4-7122-4ab5-b1a1-a72b9ccb1239)

**Comment by jcesarmobile** [comment]
thanks for the issue, it's updated now
