### ISSUE TITLE
Not a Cordova-based project

### ISSUE THREAD

**Issue by adityavyas** [ionic-team/ionic-site#166]
On the getting started page (http://ionicframework.com/getting-started/) when I checkout any template project and try adding a platform from projects root directory it gives and error saying "Not a Cordova-based project". If I am not wrong it creates a base-master directory so I need to cd in that directory and then add a platform

**Comment by GuyAvraham** [comment]
Have the same issue.
What does it mean being behind a proxy?

**Comment by isaiahb** [comment]
im also having this problem, how did you fix it?

**Comment by skol-pro** [comment]
Got the same issue, I simply removed the **ios** folder under **platform**, perform the **ionic platform add ios** command again, and it worked !
