### ISSUE TITLE
History / Back button buggy when viewed from Safari (OS X)

### ISSUE THREAD

**Issue by adityamenon** [ionic-team/ionic-site#327]
Problem: History / Clicking Back does not work on Safari 9.0.2, on OS X El Capitan

Steps to reproduce:
1. Open http://ionicframework.com/docs/
2. Click on "CSS Components" icon/link {redirected to http://ionicframework.com/docs/components/)
3. Click on "color options" link {redirected to http://ionicframework.com/docs/components/#colors}
4. Click "Back" button in Safari.
    \* User is sent back to http://ionicframework.com/docs/ page
    \* User ought to be sent to http://ionicframework.com/docs/components/

Extra notes:
The 'back' feature works on other pages where the links are simple `<a>` tags:
1. Go to https://en.wikipedia.org/wiki/European_migrant_crisis
2. Click on the "Statistics" link in the Table of "Contents" {redirected to https://en.wikipedia.org/wiki/European_migrant_crisis#Statistics}
3. Click "Back" button in Safari.
    \* Screen jumps back up to https://en.wikipedia.org/wiki/European_migrant_crisis

Curious why this is happening because the HTML for anchor tags on both pages appears to be identical.

**Comment by perrygovier** [comment]
The history stack needs to be updated. This works in v2 docs, but not v1.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
