### ISSUE TITLE
Optimize API demo build time

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#408]
Can it be distributed, cached, or limited to just the one demo at a time?

**Comment by perrygovier** [comment]
CC @drewrygh, I'll work on this, but any thoughts?

**Comment by brandyscarney** [comment]
On that note - do you think we could just use a variable for production?

Combine `variables.local` and `variables.production` and do something like this, where it gets updated if the production flag is added:

```
$production: true;

$font-path: "../fonts" !default;
$roboto-font-path: "../fonts" !default;

@if ($production == true)  {
  $font-path: "fonts";
  $roboto-font-path: "fonts";
}
```

& git ignoring the output file would be good

**Comment by drewrygh** [comment]
I like the idea of caching the demo bundles. If we can determine somehow whether a particular demo should be built, it seems like the best option. There should be a function to run a single demo, but the caching logic should be smart enough which single demos to build (ie: not sure that we would want `gulp demos --demo="modals"`).

**Comment by drewrygh** [comment]
Revisiting this -- @perrygovier is the issue the run time of the `gulp demos` task on the build server, or when building demos locally?

**Comment by perrygovier** [comment]
I don't care as much about the demos locally. @brandyscarney may disagree. CI can cache directories. let me know if that'll help. 

See if you can speed up multiple `gulp build` commands locally.

**Comment by brandyscarney** [comment]
The API demos build fast locally. I haven't seen any issues there.

**Comment by perrygovier** [comment]
Think Webpack chunks are the right way to go, but I don't know enough about Webpack to know how to use them. @tlancina, can you shed any light?
