### ISSUE TITLE
Feature request: HTML5-History navigation in docs

### ISSUE THREAD

**Issue by lebedev** [ionic-team/ionic-site#422]
I find inconvenient that after clicking on any anchor-link I can't press `Back` button in my browser to continue reading where I was before clicking anchor link.
![](http://i.imgur.com/8mwQjTe.png)
I think that it would be great if clicking those links would push a new html5-history state for the sake of docs reading navigation convenience.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
