### ISSUE TITLE
Automatically add anchor links to header tags

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#557]
Dgeni automatically adds anchor tags to members and sections in the v2 API docs. Lets automatically add anchor links to all header tags inside docs. This will probably need to be via a Kramdown plugin. The trick is to add this in a way that doesn't break other parts of the site (ID CSS name collision, links in non-docs parts of the site).

**Comment by danbucholtz** [comment]
@perrygovier, this sounds amazing. I think it would greatly improve the usability of our site. Can we revisit this?

Thanks,
Dan
