### ISSUE TITLE
Create an Advanced section for API docs

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-site#607]
Right now we're writing too much in the `@description` section of each API. Instead, we'd like to keep the description at only 1 or 2 paragraphs.

Let's create a new section called "Advanced", which is reserved for the verbose descriptions of how things work. This way the flow of the docs can go from simple to advanced as you scroll down, instead of having to put all advanced topics in the description.

Also, not really sure what the differences are between the description section, and component section. Could we combine those somehow?

Order of the sections would be:

```
  Description/Component
  Usage
  Input Properties
  Output Events
  Advanced
  Related
```

**Comment by adamdbradley** [comment]
Here's an example of an API that'd benefit from this change: http://ionic-site-staging.herokuapp.com/docs/v2/api/components/datetime/DateTime/

**Comment by brandyscarney** [comment]
Also, is there any way these main headers could show up in the side nav when viewing a component? Like a third nav that makes it easier to jump around? 

![screen shot 2016-05-17 at 6 10 04 pm](https://cloud.githubusercontent.com/assets/6577830/15341090/9a78ee5e-1c5a-11e6-852a-fca10e489386.png)

**Comment by mhartington** [comment]
Sounds like a good idea. Should be pretty easy to add.

@perrygovier did you want to handle the dgeni/sidemenu part and I can tackle the content?

**Comment by perrygovier** [comment]
@mhartington I've created the advanced section. I'll do the side nav links a bit later.

**Comment by adamdbradley** [comment]
Also, remove the "Component" section, and place the "selector" section to be under the header.

**Comment by mhartington** [comment]
Much cleaner

![screen shot 2016-06-13 at 4 32 30 pm](https://cloud.githubusercontent.com/assets/2835826/16022160/7acba60c-3184-11e6-87bb-af60df0412a4.png)
