### ISSUE TITLE
docs: Update CLI docs

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#636]
The CLI docs ([http://ionicframework.com/docs/v2/cli/](http://ionicframework.com/docs/v2/cli/)) could use some updates. Maybe add the flag for `--no-ts` and `--v2` to the start table. 

Also, it would be good to add some more info on the generate command, like that typescript gets generated if `"typescript": true` is in the ionic config: http://ionicframework.com/docs/v2/cli/generate/

In general it would be good to review all of them.

**Comment by mhartington** [comment]
In general, I wonder if we should figure out a way to automate this a bit. 
Right now the CLI docs are being generated by a gulp task in ionic-site.

Not ideal if we have to manually do this.


Also note, we should remove the livereload comments from the emulate/run commands. These have been broken with security changes in cordova and ios/android.

**Comment by danielsogl** [comment]
@brandyscarney this issue can be closed
