### ISSUE TITLE
Add NavParams to component docs

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#641]
Since NavParams are commonly used in Ionic 2 applications we should have some mention of them in the main component docs. Currently you have to go to the api docs to get a direct menu item to NavParams, therefore there a little hard to find considering how commonly they are used.

**Comment by mhartington** [comment]
I really don't think we should mention them in the component docs. Since they're less of a 'component' and more of just a generic API, it doesn't really make sense. Though we could link to them from the navigation component doc instead?

**Comment by jgw96** [comment]
A link to them from the nav component doc might not be a bad idea. Max mentioned that even though it was a pretty commonly used part of Ionic 2, the NavParams docs were pretty hard to find.

**Comment by brandyscarney** [comment]
We could add a section after Basic Navigation that is something like "Navigating with Parameters" or "Passing Data with Navigation" and link to the NavParam API docs that way?

**Comment by jgw96** [comment]
Thats not a bad idea. Keeps the NavParam docs in the api docs, but makes them easier to find at the same time.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
