### ISSUE TITLE
explain the difference between the page and component generators

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#686]
Since we do not have the `@Page` decorator anymore the difference between the component generator and the page generator is a little confusing now. For example, you should use the page generator if you wanted to use that generated component as a page or modal, but since we changed from `@Page` to `@Component` it almost seems like you would use the component generator. If you try to use the component generator you will get weird issue because the component generator puts a selector on the component.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
