### ISSUE TITLE
Missing documentation on NavOptions

### ISSUE THREAD

**Issue by kz** [ionic-team/ionic-site#714]
It is currently unclear what a few NavOptions (such as `climbNav` and `ev`) are for. It would be useful to document these.

Related: https://github.com/driftyco/ionic/issues/5754#issuecomment-193287250

**Comment by callodacity** [comment]
Do we have a list of possible values for `NavOptions` too?
I can't seem to find any documentation for valid values for `animation` or `direction`. The website only says:

> `animation`	 _string_	What kind of animation should be used.
> `direction`	_string_	The conceptual direction the user is navigating. For example, is the user navigating `forward`, or `back`?

According to the docs, the only possible values for `direction` are `forward` or `back`. And there are no documented values for `animation`. 
How can we find out what values we can use here to customise transitions?

**Comment by AsimNet** [comment]
up

**Comment by radvansky-tomas** [comment]
Any update on this ? Could you please post possible values for animation ?

**Comment by zeeshananjumjunaidi** [comment]
if you read documentation https://ionicframework.com/docs/api/navigation/NavController/
it says:
The property 'animation' understands the following values: **md-transition, ios-transition** and **wp-transition**.
direction is **forward** and **back**.
duration is the length in milliseconds the animation should take.
I used following to test:
``` typescript
      this.navCtrl.pop({ duration: 1000, animation: "wp-transition", animate: true });
      this.navCtrl.push(SETTINGS, [],
          { duration: 1000, animation: "ios-transition", animate: true });
```

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
