### ISSUE TITLE
docs: presenting overlays should not be done in constructor

### ISSUE THREAD

**Issue by Kobzol** [ionic-team/ionic-site#748]
It would be useful to add a warning to the docs that users should not present overlays (and generally work with UI or navigation) in the constructor of components, they should use the lifecycle events (i. e. `ionViewDidEnter`. See https://github.com/driftyco/ionic/issues/7602.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
