### ISSUE TITLE
forwardRef() in docs -> FAQ

### ISSUE THREAD

**Issue by shlomiassaf** [ionic-team/ionic-site#764]
Short description of the problem:

Docs suggests using forwardRef() in Common Pitfalls

What behavior are you expecting?

Do not suggest usingforwardRef or at least add a section with a note suggesting the issue is probably caused due to a problem in the design.

Usually forwardRef is used in advanced scenarios in the framework (i.e: ionic, angular core) and should rarly occur in the application code itself. It can be avoided by using a better design.
I have seen lot's of question/scenarios in Gitter that a forwardRef will indeed solve quickly but they actually happen due to poor design. A developer reading the common pitfalls will "run" to implement that advice just to encounter issues later. Again, usually it's due to poor design in the service layer. I believe the angular team will also discourage the use of forwardRef as much as possible.

Which Ionic Version? 2.x

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
