### ISSUE TITLE
Doc error - supportedImageModes in Media Capture

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#766]
_From @chrisbenseler on August 23, 2016 18:34_

In the [Media Capture](http://ionicframework.com/docs/v2/native/media-capture/), supportedImageModes() method description says:

"The audio recording formats supported by the device."

Is it right? The method name is about Image, the description is "audio recording".

_Copied from original issue: driftyco/ionic#7840_

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
