### ISSUE TITLE
Update Ionic repo dgeni/dgeni-packages version

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-site#770]
Ionic's repo is using an outdated version of dgeni, and the version we're using has many outdated dependencies, which always print out deprecated warnings. I didn't update the versions myself in fear the site would blow up and melt my desktop. 💥 

https://www.npmjs.com/package/dgeni
https://www.npmjs.com/package/dgeni-packages

**Comment by perrygovier** [comment]
driftyco/ionic-cloud uses a copy of this repo's dgeni setup, but has been upgraded to the latest version of dgeni and dgeni-packages. It provides a lot of additional data for us to use, but takes a little refactoring to make work.

**Comment by perrygovier** [comment]
Let's do this in three steps. 

- [ ] Upgrade Dgeni so that there are no more warnings
- [ ] Apply updated version's new data to Ionic Native docs
- [ ] Apply update version's new data to Ionic v2 docs

**Comment by danielsogl** [comment]
@adamdbradley this issue can be closed I think
