### ISSUE TITLE
Navbar layout issue with short API docs

### ISSUE THREAD

**Issue by tlancina** [ionic-team/ionic-site#772]
Ex: http://ionicframework.com/docs/v2/api/components/toolbar/Header/

![image](https://cloud.githubusercontent.com/assets/804331/18110481/dc8da728-6edd-11e6-9f58-27a35be48d63.png)

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
