### ISSUE TITLE
SqlStorage docs -- note Sqlite plugin dependency?

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#779]
_From @tycho01 on September 17, 2016 7:32_

The [SqlStorage doc](https://github.com/driftyco/ionic/blob/master/src/storage/sql.ts) currently does not mention its dependency on 
the [SQLite](http://ionicframework.com/docs/v2/native/sqlite/) plugin. If not added this can lead to errors on mobile: `SecurityError: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.`

_Copied from original issue: driftyco/ionic#8106_

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
