### ISSUE TITLE
bug:back button not show sometimes in official docs(1.3.1)

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#787]
_From @Sunzhuokai on September 23, 2016 4:9_

back button not show sometimes in this page http://ionicframework.com/docs/api/directive/ionNavView/

click follow this steps 
1. About tab→Tabs NavStack(back button show)→Click back button
2.  swipe to Home tab→Scientific Facts→swipe to About tab→Tabs NavStack(back button not show)

can fix this?

_Copied from original issue: driftyco/ionic#8180_

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
