### ISSUE TITLE
Outdated info in docs..

### ISSUE THREAD

**Issue by jgrantr** [ionic-team/ionic-site#802]
I'm not sure what version of Ionic this applies to, but I've put the URL below.

The information on this page:

http://ionicframework.com/docs/guide/testing.html

is outdated. Under the section "Testing as a native app", it incorrectly states that it costs $99 per year to test an iOS app on a device. It has been free to test on a device since at least June 2015. Probably best not to leave information that is over a year out of date in the docs. Certain things still require a paid membership, but basic testing on a device is not one of them.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
