### ISSUE TITLE
Update getting started guide.

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-site#807]
https://github.com/driftyco/ionic/issues/8359

The older guide was "meh" to begin with.
We can do better. Just need to sit down and "do it"

**Comment by simonh1000** [comment]
+1 for an update. Hopefully my subscription to this issue will mean I get a notice when Ionic 2 is ready for first-timers again

**Comment by HellerCommaA** [comment]
Looks like the tutorial base project is out of sync with the documentation as well.  Specifically 
[http://ionicframework.com/docs/v2/getting-started/tutorial/navigation/](http://ionicframework.com/docs/v2/getting-started/tutorial/navigation/) ```Let’s import it in app/pages/list/list.ts so we can use it:``` that import is already included in the mentioned file.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
