### ISSUE TITLE
alert scrolling not working in components page

### ISSUE THREAD

**Issue by azza85** [ionic-team/ionic-site#817]
Hi Ionic team, great work on the recent updates, its an exciting time for hybrid apps!
One think I noticed on the components page was that that the scrolling in the alert box does not seem to work eg radio/checkbox scroll http://ionicframework.com/docs/v2/components/#alert you can also see this on the select example (try gaming)

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not seeing this in the docs. Are you still able to reproduce this?

**Comment by azza85** [comment]
@brandyscarney I still seem to get it in my chrome browser eg in the below screen shot i cant scroll down to see what ever is under Hoth it seems like the scroll doesn't work?

http://ionicframework.com/docs/v2/components/#alert-checkbox

<img width="370" alt="817" src="https://cloud.githubusercontent.com/assets/4461762/19514765/86105e60-9640-11e6-9bf5-e9592de288d7.png">

Let me know if you need more info.
Thanks

**Comment by brandyscarney** [comment]
@azza85 What OS & version, as well as Chrome version are you using?

**Comment by azza85** [comment]
@brandyscarney 
Macintosh OS X 10.11.6
Chrome 54.0.2840.59

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
