### ISSUE TITLE
Pick either ./config or ./scripts for custom config placement

### ISSUE THREAD

**Issue by patrickmcd** [ionic-team/ionic-site#823]
In the new app-scripts resource doc (docs/v2/resources/app-scripts/index.md), under "Providing Custom Build Configuration," the placement for the custom config file is:

`"ionic_rollup": "./config/rollup.config.js"`

Later, under "Third Party Modules Export Errors," it is:

`"ionic_rollup": "./scripts/rollup.config.js"`

This can only add confusion to an already confusing subject. I'd pick one as the convention and scrap the other.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
