### ISSUE TITLE
Sidenav is included when printing docs

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-site#828]
When printing documentation, the side navigation is not been hidden and is being overlaid on the content.

![screen shot 2016-10-11 at 9 51 58 am](https://cloud.githubusercontent.com/assets/527875/19279946/61df915e-8f98-11e6-8ad1-966c3c68633e.png)

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
