### ISSUE TITLE
Change how resources sub-nav works

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#844]
Drop individual side links from the side menu navigation. Instead, anchor link to sections within the resources page.

**Comment by brandyscarney** [comment]
Just in case no one looks at this for awhile, adding some info:

Sections on resource page:

```
Videos
link
link 
link

How to
link 
link
link
```

then in the side menu, anchor links to headers

```
Resources
  Videos
  How to
  ...
```

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
