### ISSUE TITLE
Document steps for using ionic with non-ionic build

### ISSUE THREAD

**Issue by abierbaum** [ionic-team/ionic-site#845]
Sorry if this isn't the correct place to request documentation additions.

I would like to add an Ionic 2 progressive web app (ie. non-native just standard ng2 app) to our existing set of Angular 2 applications managed by our webpack build. Is there a set of instructions for how to build an Ionic app outside of the ionic cli?   We already have angular2 and all the build setup working for sass, minification, etc.  We just want to add another angular2 application to the mix that uses ionic2.

More specifically, I would like to get ionic building inside a build for multiple web applications that is based on https://github.com/AngularClass/angular2-webpack-starter3. The main thing I am trying to solve is how to create the base scss file that imports everything core needed by ionic?  (rules, assets, fonts, etc)

Is this something that could be documented to help people that are not using the ionic command line tool or app-scripts?

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
