### ISSUE TITLE
Expectations of where to find stuff in docs

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-site#852]
Forgive the odd title, I wasn't sure exactly how to name it. Today I was trying to find the docs for `<ion-scroll>`, which I naturally expected to find under Components, but instead it was under API. But it isn't an API. I mean I assume it has an API to work with it, but it's a component, so why isn't it there?

(As a general FYI, I feel like this has been an issue with the Ionic docs for a while. I know that's nice and vague, just sharing my feelings. ;)

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
