### ISSUE TITLE
Ionic resources - icon template file

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-site#862]
The download link for the icon template psd file is weird. It should be similar to the splash template psd. 

Splash: http://code.ionicframework.com/resources/splash.psd
Icon: https://docs.google.com/viewer?url=http%3A%2F%2Fcode.ionicframework.com%2Fresources%2Ficon.psd

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
