### ISSUE TITLE
Device image doesn't display fully and can't scroll

### ISSUE THREAD

**Issue by m5rk** [ionic-team/ionic-site#872]
The device image on the right hand side of the docs; e.g.,

http://ionicframework.com/docs/v2/components/#action-sheets

is not fully visible on my 13" MacBook Pro and I can't scroll to see the bottom.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
