### ISSUE TITLE
ionic2.rc0: ionViewCanLeave and Navbar back button issue:

### ISSUE THREAD

**Issue by A-EL** [ionic-team/ionic-site#873]
Hello,
 I have situation similar to the one documented [here]: (https://github.com/driftyco/ionic-site/issues/829)

BUT in my case, i'm using the NavBar back button.

**What i'm trying to do is:**
1- Have a page - let's call it index - with an 'add' button. when i click the 'add' button, it pushes another  page (will call it 'addPage')
2- 'addPage' contains 2 input fields. Any change on those fields will set a flag to true.
3- When the user clicks the back button on the NavBar, i'll check on ionViewCanLeave and If the flag equals to true, i'll ask the user to confirm losing changes.

my ionViewCanLeave code would be like this:

>
ionViewCanLeave():
>

    ionViewCanLeave(){ if(this.formData.isModified ===true) //input filed modified
        {           
            let alert: Alert = this.alertCtrl.create({
            title: 'confirm',            
            buttons: [{
                    text: 'Yes'
                    handler: () => { //when returning, ionViewCanLeave will be called again, and after setting this to false, it will return true.
                            this.formData.isModified =false;  
                                this.nav.pop(); }
                },
                {
                    text: 'No',
                    role: 'cancel',
                    handler: () => {}
                }]
            });
            alert.present();
            return false;
        }
        else return true;
    }
**What i expect:**
If the user clicked yes on the alert, he will go back to the 'index' page.

**What i get:**
a blank page with no console errors!

I should mention that even if i didn't use Alert and just put code like that, i get the same result:
>
c: any = null;
ionViewCanLeave(){ 
   if(c==null){c=1; return false;} 
   else return true;
}

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
