### ISSUE TITLE
Icon docs for v2 show incorrect (misleading) name

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-site#882]
When you search for an icon here, http://ionicframework.com/docs/v2/ionicons/, and enter something like "facebook", the results will show a name column and will say facebook. But that's the name you use in code. You have to click the icon to see "logo-facebook". This is pretty misleading.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. The modern docs simply link to ionicons.com that makes this distinction.
