### ISSUE TITLE
DateTime configuration documentation is stale

### ISSUE THREAD

**Issue by rapropos** [ionic-team/ionic-site#905]
The "App Level Config" section of [the documentation for the DateTime component](https://ionicframework.com/docs/v2/api/components/datetime/DateTime/) refers to outdated bootstrap procedures. It needs to be updated to reflect current `@NgModule`-style structure.

**Comment by ramification** [comment]
it seems that the app level config for locales have been removed, this is really a problem !

i've tested in multiple ways :

```js

      // those ones work as expected
      config.set('backButtonText', 'Retour')
      config.set('tabsLayout', 'icon-top')
      config.set('tabsHighlight', true)
      config.set('tabsHideOnSubPages', false)

      // datetime config does not work
      config.set('locale', {
        monthNames      : moment.months(),
        monthShortNames : moment.monthsShort(),
        dayNames        : moment.weekdays(),
        dayShortNames   : moment.weekdaysShort(),
      })
      config.set('monthNames', moment.months())
      config.set('monthShortNames', moment.monthsShort())
      config.set('dayNames', moment.weekdays())
      config.set('dayShortNames', moment.weekdaysShort())

```

**Comment by gmarcos87** [comment]
Can I do this globally?

**Comment by brandyscarney** [comment]
Just noticed this as well. We need to remove the references to `ionicBootstrap` here. 

<img width="718" alt="screen shot 2017-02-28 at 11 49 16 am" src="https://cloud.githubusercontent.com/assets/6577830/23415048/f54c5752-fdab-11e6-9557-366002be9a9c.png">

**Comment by fredcox** [comment]
Today is 2020, Ionic is Version 5 and i cant use datetime ui component in portuguese brazil language because this framework not support.

**Comment by mhartington** [comment]
Hello @fredcox. If there is an issue with the component, please open an issue on the main repo. This is for documentation

**Comment by fredcox** [comment]
No problem, i switch to React Native and i very happy. Cheers
