### ISSUE TITLE
Add toc to the FAQ

### ISSUE THREAD

**Issue by amuramoto** [ionic-team/ionic-site#906]
The [FAQ](http://ionicframework.com/docs/v2/faq/) is very long and hard to scroll through to find useful info. Consider adding a table of contents to the top of this page.

**Comment by amuramoto** [comment]
Also to API doc pages

**Comment by perrygovier** [comment]
This is part of the restructuring branch and issue #939

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
