### ISSUE TITLE
Refactoring suggestions for Concepts

### ISSUE THREAD

**Issue by amuramoto** [ionic-team/ionic-site#916]
A couple suggestions for refactoring the docs to maybe consider.

The Concepts section under 'Setup' doesn't appear to make sense. It does not have any info on setting up. Much of the content would be better under FAQ, or fleshed out and featured more prominently under a top-level Concepts item that more fully describes the topology of an ionic project. 

There's also  some info that might be better under an 'About' page. For example, the 'What is Ionic Framework?' and 'Who is behind Ionic?' sections.

**Comment by perrygovier** [comment]
I like that categorization better. The current setup page was previously called "getting started", and was renamed to "setup" to avoid having two "getting started" pages when the main getting started page was updated to v2.

**Comment by amuramoto** [comment]
It would require some additional content, but I think a full look at the 'building blocks' of an Ionic app  could be a big benefit to users. 

Maybe change 'Setup' to 'Introduction'?

**Comment by mhartington** [comment]
This echoes some idea we had in a framework meeting today, where we have random bits of info or tips to share, but no clear section to put them

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
