### ISSUE TITLE
docs: can't scroll search results or reach general when native has a lot

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#921]
If I search for something like `android` on the [v2 docs site](http://ionicframework.com/docs/v2) it gives me a lot of results in Native and prevents me from being able to see what is in General:

<img width="1148" alt="screen shot 2016-12-05 at 3 28 16 pm" src="https://cloud.githubusercontent.com/assets/6577830/20901300/e1c1e02e-baff-11e6-9b54-8b51246351af.png">

If I try scrolling down it scrolls the background but not the search results:

<img width="1377" alt="screen shot 2016-12-05 at 3 29 25 pm" src="https://cloud.githubusercontent.com/assets/6577830/20901301/e1c4534a-baff-11e6-870b-5f64f0e62050.png">

**Comment by goodells** [comment]
Would you be able to verify that this is still a problem, or provide more detailed steps for reproducing the issue?  I've been able to scroll the search results fine on my desktop & phone.

**Comment by brandyscarney** [comment]
@goodells Yes it is still a problem, go to any API page such as: http://ionicframework.com/docs/api/components/avatar/Avatar/

Type in `android` in the top left searchbar & then try to scroll the page. I am using Chrome Version 59.0.3071.115

Feel free to ping me if you need me to show you. 😄

**Comment by goodells** [comment]
@brandyscarney I figured it out - I was using the big search box in the middle and not the one on the top.  I submitted a fix for it and it seems to take care of it with a little flexbox magic, but would you mind taking a look at the pull?

**Comment by brandyscarney** [comment]
@goodells Looks good to me 👍
