### ISSUE TITLE
Font color is hard to read in documentation. 

### ISSUE THREAD

**Issue by alexmgrant** [ionic-team/ionic-site#930]
Hey guys look at the font for the attribute documentation. http://ionicframework.com/docs/v2/theming/css-utilities/  

It's madness. I'm getting older maybe, but this is straight up hard to read.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
