### ISSUE TITLE
Component list is not complete

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-site#934]
So a few minutes ago I discovered there was an `<ion-note>` component. I had no idea this existed because the Component list doesn't include it. After speaking w/ Mike a bit, he pointed out that the list there is not meant to be exhaustive, and I see that, but do not agree with it. Nowhere is it implied (to me anyway ;) that the list isn't a complete list of `<ion-*>` controls. I think folks will assume it is. I'd argue for:

a) Either include EVERYTHING in that list
b) Make the overview (http://ionicframework.com/docs/v2/components/#overview) include text making it VERY clear this isn't an exhaustive list
c) and if B is chosen, and a list. Yes, I know API has everything, but it mixes components with code-level stuff and I think a proper list of *just* the component stuff would be useful.

**Comment by cfjedimaster** [comment]
Just to add a bit more to this: Consider <ion-card>. It is listed in Components, but not API. So maybe there isn't an API for Cards, but now the argument that API has everything doesn't make sense.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. I think it's safe to say this is a `wontfix` for v2, but v4 docs automatically document every component so this should be a non-issue for current versions
