### ISSUE TITLE
documentation for picker is missing?

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#935]
_From @danishin on December 21, 2016 6:52_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Not sure if this is intended or not (perhaps it's meant to be a private api?), but lately I've been using `PickerController` and `Picker` classes for creating custom picker and noticed doc is missing. What's the state on this?

_Copied from original issue: driftyco/ionic#9742_

**Comment by tmvnk** [comment]
@brandyscarney I'm also interested in this API? Especially related to issue: driftyco/ionic/issues/7333

**Comment by sykaeh** [comment]
The documentation for the Picker API is mentioned in the docs for `ion-datetime` (https://ionicframework.com/docs/api/components/datetime/DateTime/). However, the link (https://ionicframework.com/docs/api/components/picker/Picker) is broken since it redirects (https://ionicframework.com/docs/v1/api/components/picker/Picker) and then leads to a 404. 

It would be great to have the docs for the picker or else remove the broken link.

**Comment by davl3232** [comment]
There's a small explanation of how it's used [here](https://github.com/ionic-team/ionic/issues/15099#issuecomment-411879817). I really wish there was more though.

So far I've tried using it as explained there, it does show up, but it appears broken for some reason.

![screenshot from 2018-10-10 13-39-46](https://user-images.githubusercontent.com/4100566/46758352-3ae24900-cc92-11e8-8045-04e7483280d3.png)

**Comment by brandyscarney** [comment]
@davl3232 There is an open bug for that here: https://github.com/ionic-team/ionic/issues/15579

The picker needs `selectedIndex` to be set: https://github.com/ionic-team/ionic/issues/15579#issuecomment-422860130

This is most likely a bug with picker, but I haven't had time to look into it.

**Comment by davl3232** [comment]
> @davl3232 There is an open bug for that here: [ionic-team/ionic#15579](https://github.com/ionic-team/ionic/issues/15579)
> 
> The picker needs `selectedIndex` to be set: [ionic-team/ionic#15579 (comment)](https://github.com/ionic-team/ionic/issues/15579#issuecomment-422860130)
> 
> This is most likely a bug with picker, but I haven't had time to look into it.

Thank you!

**Comment by brandyscarney** [comment]
I'm going to close this as picker has been documented in v4: https://beta.ionicframework.com/docs/api/picker

It is unlikely we will document it for v3. Please create an issue on the [ionic-docs](https://github.com/ionic-team/ionic-docs) repository if you find a problem with this documentation. Thanks!
