### ISSUE TITLE
Date picker API link is broken in v2 docs.

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#937]
_From @sudharsanmit on December 20, 2016 7:43_

Datepicker API is broken in v2 docs. Pls fix.

https://ionicframework.com/docs/v2/api/components/picker/Picker

There is a reference to the above link here

> pickerOptions	any	
> Any additional options that the picker interface can accept. See the Picker API docs for the picker options.

-- Source: https://ionicframework.com/docs/v2/api/components/datetime/DateTime/

_Copied from original issue: driftyco/ionic#9719_

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
