### ISSUE TITLE
bug(ion-content): content vertically scrollable on iOS

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#940]
_From @dylanvdmerwe on December 12, 2016 19:53_

**Ionic version:**  (check one with "x")
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
I have a simple `ion-slides` component. On Android the content is locked. However the same code on iOS the user is able to scroll the screen up and down. This makes the app feel 1000% non-native. Note that this was not happening in RC3 but now in the latest nightly this behaviour is happening. 

*edit: This appears to be happening on any screen without an `ion-header`!*

Has something changed? Why would this work correctly on Android and not on iOS?

See below:

![scrolling_issue](https://cloud.githubusercontent.com/assets/2852839/21114234/1d39caa8-c0b5-11e6-82aa-7f9897ac45b3.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612100458
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

_Copied from original issue: driftyco/ionic#9604_

**Comment by jgw96** [comment]
_From @dylanvdmerwe on December 12, 2016 21:8_

This seems to be happening on any screen without an `ion-header` on iOS 10.1. Works as expected on Android.

**Comment by jgw96** [comment]
_From @dylanvdmerwe on December 14, 2016 14:54_

My issue is that a screen without an `ion-header` should not automatically scroll. It gives away that the app is not native. 

To get around this, for now, we use the following:
```
.no-scroll {
    div.scroll-content {
        overflow-y: hidden;
    }
```

Then on any `ion-content` screens that we wish to not scroll:
```
<ion-content class="no-scroll">
```

**Comment by jgw96** [comment]
So for anyone else running into this issue, adding the `no-bounce` attribute to your `ion-content` will do the trick. This is actually a docs issue as we do not currently document `no-bounce` anywhere.

**Comment by jgw96** [comment]
Update: alex is gonna take care of documenting this attribute

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
