### ISSUE TITLE
Information on adding pages in the tutorial doesn't match what's generated in a tutorial app

### ISSUE THREAD

**Issue by jwithington** [ionic-team/ionic-site#944]
Over on [this page](https://ionicframework.com/docs/v2/setup/tutorial/adding-pages/), the following text appears:

> Below, we see the HelloIonicPage class. This creates a Page - an Angular component with all Ionic directives already provided, to be loaded using Ionic's navigation system. Notice that because Pages are meant to be loaded dynamically, they don't have a selector:

```import {Component} from '@angular/core';

@Component({
  templateUrl: 'build/pages/hello-ionic/hello-ionic.html'
})
export class HelloIonicPage {}
```

However, when I built a tutorial app, the hello-ionic-ts page actually contained:

```
import { Component } from '@angular/core';


@Component({
  selector: 'page-hello-ionic',
  templateUrl: 'hello-ionic.html'
})
export class HelloIonicPage {
  constructor() {

  }
}
```

Relevant github page is [here](https://github.com/driftyco/ionic-site/blob/61c7a597c96a22679807e5b6f2a07a80b6d1a7df/content/docs/v2/setup/tutorial/adding-pages/index.md).

Hope this helps!

**Comment by rushabhshah011** [comment]
@perrygovier @jwithington @mhartington Please review PR : Changes doc according source code in file #1385
