### ISSUE TITLE
Document ion-app platform classes

### ISSUE THREAD

**Issue by tlancina** [ionic-team/ionic-site#952]
For example, on iOS on the simulator the following classes are added: `ios platform-cordova platform-mobile platform-ios platform-ios10 platform-ios10_1 platform-iphone`.

**Comment by brandyscarney** [comment]
Could steal some from here: http://ionicframework.com/docs/platform-customization/platform-classes.html

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
