### ISSUE TITLE
Update config values in Config API docs

### ISSUE THREAD

**Issue by tlancina** [ionic-team/ionic-site#958]
http://ionicframework.com/docs/v2/api/config/Config/

`scrollAssist` is missing, there may be others. Perhaps something we can autogenerate with Dgeni?

**Comment by goodells** [comment]
Just a note to myself when I take care of this - the [theming documentation](http://ionicframework.com/docs/theming/platform-specific-styles/) will probably need to be updated with any new/missing config properties as well.

**Comment by goodells** [comment]
I did some searching through the Ionic source and here are the undocumented config properties that I think might need to be added.  @perrygovier would you be able to advise about how to filter out which of these are actually relevant?

#### Booleans

`animate`
`clickBlock`
`disableScrollAssist`
`hideCaretOnScroll`
`hoverCSS`
`inputBlurring`
`keyboardResizes`
`navExitApp`
`preloadModules`
`resizeAssist`
`scrollAssist`
`scrollPadding`
`spellcheck`
`statusbarPadding`
`tapPolyfill`
`virtualScrollEventAssist`

#### Numbers

`imgRenderBuffer`
`imgRequestBuffer`
`imgVelocityMax`
`keyboardHeight`
`pickerRotateFactor`
`pickerScaleFactor`

#### Unknown type

`activatedClass`
`autocomplete`
`autocorrect`
`autoFocusAssist`
`focusOutline`
`infiniteLoadingSpinner`
`ionPullIcon`
`ionRefreshingSpinner`
`spinner`

**Comment by goodells** [comment]
Perry says that this question would be better for you, @mhartington.  Would you have any idea what to do with all of these?  It looks like mostly strings are documented currently, but this includes more numbers and booleans.

**Comment by brandyscarney** [comment]
I just want to jump in and add that some of these _shouldn't_ be documented as they are internal config options that we would prefer them not to change. We'll have to go through each of them to determine which though.

`spellcheck`, `autocomplete`, and `autocorrect` probably came from input? I'm not sure why those are even global config level.

**Comment by goodells** [comment]
That's a good point - I didn't make any distinction between global vs. component-specific properties here, it's just a dump of everything from the source.  But wouldn't these still be applicable at the global level if they are inherited by e.g. an input component?

**Comment by brandyscarney** [comment]
Yes I was more questioning what benefit there is to  us allowing them to be globally changed, but I believe it was so users could change all inputs to have `autocomplete` (and the others) off or on without having to individually add the attribute to each input in their app.

**Comment by goodells** [comment]
Maybe we could categorize the config properties in this page, or indicate on the API documentation pages of the components which config properties affect them?  For example, there could be something that says the `autocomplete` config property will affect an `Input`.  Or a set of `Input`-related properties.
