### ISSUE TITLE
docs: create a section for instance properties

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-site#961]
Add a section for `Instance Properties` similar to `Instance Methods` to document the properties that a class has. The major use case for this is to document the properties `Slides` has available that aren't inputs. See: https://github.com/driftyco/ionic/blob/master/src/components/slides/slides.ts#L334-L610

**Comment by perrygovier** [comment]
We're going to leave Properties together with Methods under the "Members" title

**Comment by perrygovier** [comment]
Let's revisit this post-2.0

**Comment by perrygovier** [comment]
In some classes, there are a ton of properties and we don't really need each property to be linkable like methods are. At the start of each Instance Members section, let's have a properties table similar to the input properties table.
