### ISSUE TITLE
Section on debugging

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#976]
A section on basic debugging, such as how to use chrome://inspect to inspect the webview or a chrome tab in android or how to use safari to debug on iOS would be pretty useful to our users. Not sure where something like that should go in the docs, but im thinking as maybe part of the getting started section.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
